name: Build and Generate APK for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npm install @capacitor/core @capacitor/cli
          
      - name: Initialize Capacitor
        run: |
          npx cap init "LuvvixApp" "com.luvvix.chatbot" || echo "Capacitor already initialized"
          npx cap add android || echo "Android platform already added"

      - name: Build Vite.js app
        run: |
          npm run build || { echo 'Vite build failed'; exit 1; }

      - name: Sync Capacitor with Android
        run: |
          npx cap sync || { echo 'Capacitor sync failed'; exit 1; }

      - name: Copy the build to Android
        run: |
          npx cap copy android || { echo 'Capacitor copy failed'; exit 1; }

      - name: Install Android dependencies
        run: |
          cd android && ./gradlew clean
          cd android && ./gradlew dependencies || { echo 'Gradle dependencies installation failed'; exit 1; }

      - name: Build APK (Release)
        run: |
          cd android
          ./gradlew assembleRelease || { echo 'APK build failed'; exit 1; }

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Clean up
        run: |
          rm -rf android/app/build || echo "No build folder to clean"