name: Build APK with Gradle and Capacitor

on:
  push:
    branches:
      - main  # Déclenchement du workflow sur chaque push vers la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu

    steps:
    - name: Checkout code
      run: git clone https://github.com/ludagg/luvvix-chatbot-muse-33.git .  # Clone directement le code du dépôt

    - name: Install Node.js and npm dependencies
      run: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -  # Installe Node.js 16
        sudo apt-get install -y nodejs  # Installe Node.js sur l'environnement
        npm install  # Installe toutes les dépendances de ton projet Node.js

    - name: Install Java
      run: |
        sudo apt update
        sudo apt install openjdk-11-jdk -y  # Installe Java 11 nécessaire pour Gradle

    - name: Install Capacitor Android platform
      run: |
        npx cap add android  # Si tu n'as pas déjà ajouté Android, sinon tu peux ignorer cette étape

    - name: Build the project
      run: |
        npm run build  # Compile ton projet Vite.js

    - name: Build APK using Gradle
      run: |
        cd android  # Va dans le dossier android
        ./gradlew assembleDebug  # Compile le projet Android en mode Debug

    - name: Upload APK as artifact
      run: |
        mkdir -p /tmp/artifacts  # Crée un dossier temporaire pour stocker l'APK
        cp android/app/build/outputs/apk/debug/app-debug.apk /tmp/artifacts/  # Copie l'APK généré
        ls -l /tmp/artifacts  # Vérifie que l'APK a bien été copié

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2  # Utilisation de l'action GitHub pour télécharger l'APK
      with:
        name: luvvix-apk  # Nom du fichier APK
        path: /tmp/artifacts/app-debug.apk  # Emplacement du fichier APK
