name: Build APK with Capacitor and Gradle

on:
  push:
    branches:
      - main  # Déclenchement sur chaque push vers la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation d'une machine Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      run: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Install npm dependencies
      run: |
        npm install

    - name: Install Capacitor dependencies
      run: |
        npm install @capacitor/core @capacitor/cli @capacitor/android

    - name: Initialize Capacitor
      run: |
        npx cap init "Luvvix Chatbot" "com.ludagg.luvvixchatbot"  # Remplace par ton nom et appId

    - name: Add Android platform
      run: |
        npx cap add android

    - name: Ensure capacitor.settings.gradle exists
      run: |
        echo "rootProject.name = 'android'" > android/capacitor.settings.gradle
        echo "include ':app'" >> android/capacitor.settings.gradle
        echo "apply from: '../node_modules/@capacitor/android/capacitor.settings.gradle'" >> android/capacitor.settings.gradle

    - name: Build the project
      run: |
        npm run build

    - name: Build APK using Gradle
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-file
        path: android/app/build/outputs/apk/debug/app-debug.apk