name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install dependencies
        run: |
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/android

      - name: Install custom icons
        run: |
          unzip android-icons.zip -d .
          cp -r android-icons/* android/app/src/main/res/

      - name: Build project
        run: npm run build

      - name: Configure Capacitor
        run: |
          npx cap init "LuvviX" "com.ludagg.luvvixchatbot" --web-dir=dist
          npx cap add android
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk